### PR TITLE
Add data access layer

### PR DESCRIPTION
**Pull request by AvivSela**

### CODE REVIEW

**Comment by EyalBerger** [comment]
I am getting an error for SiriRecord - 

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-17-51098f3ca47b> in <module>
     22                 response_timestamp=d,
     23             expected_arrival_time=e,
---> 24             current_location = GeoPoint(b,a)) for a,b,c,d,e in zip(*records.values())]))

<ipython-input-17-51098f3ca47b> in <listcomp>(.0)
     22                 response_timestamp=d,
     23             expected_arrival_time=e,
---> 24             current_location = GeoPoint(b,a)) for a,b,c,d,e in zip(*records.values())]))

<ipython-input-16-4f945b1f04e0> in __init__(self, recorded_at, response_timestamp, expected_arrival_time, current_location)
     72         self.recorded_at: time = recorded_at.replace(microsecond=0)
     73 
---> 74         self.response_timestamp: datetime = response_timestamp.astimezone()
     75         self.expected_arrival_time: time = expected_arrival_time.replace(microsecond=0)
     76         self.current_location: GeoPoint = current_location

pandas/_libs/tslibs/timestamps.pyx in pandas._libs.tslibs.timestamps.Timestamp.tz_convert()

TypeError: tz_convert() takes exactly 2 positional arguments (1 given)


I changed (locally) `self.response_timestamp: datetime = response_timestamp.astimezone()` to `self.response_timestamp: datetime = response_timestamp.tz_localize('Asia/Tel_Aviv')` to make it work.

**Comment by EyalBerger** [comment]
Two more comments:
1. Using pymongo requires MongoDB to be installed on your PC. I suggest add this note as a code comment or in README file. I followed this instructions from stakoverflow - 

In order to run MongoDB,

You should have installed MongoDB into your OS, download it from https://www.mongodb.com/download-center/community?tck=docs_server
Add the installation's bin folder to your system environment variables.
Openup the terminal and check 'mongod' and 'mongo' commands are working.
Then try to rerun your python script.   

2. I got issues with inserting int attributes (e.g operator_ref) and had to change them to string to make them work.

**Comment by AvivSela** [comment]
> pandas/_libs/tslibs/timestamps.pyx in pandas._libs.tslibs.timestamps.Timestamp.tz_convert()
> TypeError: tz_convert() takes exactly 2 positional arguments (1 given)
> 
> I changed (locally) self.response_timestamp: datetime = response_timestamp.astimezone() to self.response_timestamp: datetime = response_timestamp.tz_localize('Asia/Tel_Aviv') to make it work.

it is look like pandas error. i didn't use that library at all.  [astimezone()](https://docs.python.org/3/library/datetime.html#datetime.datetime.astimezone) will add to the given timestamp the default OS time zone.

**Comment by AvivSela** [comment]
> SiriRideMongoCrud(MongoCrud(MongoClient(), self.database_name))

for creating _SiriRideMongoCrud_ object you need to provide _MongoCrud_ instance and for creating this you should provide [MongoClient ](https://api.mongodb.com/python/current/api/pymongo/mongo_client.html#pymongo.mongo_client.MongoClient)instance that configure the connection to mongodb. by default it is trying to connect to localhost with mongodb known port (27017), but you could change it. for example:

> SiriRideMongoCrud(MongoCrud(MongoClient(host=10.100.34.32, port=5002), "openbus_db"))

**Comment by AvivSela** [comment]
> I got issues with inserting int attributes (e.g operator_ref) and had to change them to string to make them work.

in my tests (data_stream/test_data_access_layer.py) i created the following SiriRide and that worked for me. As you can see operator_ref is int (operator_ref=4). Could you provide me the instance that didn't worked for you, so i can add it to my tests? 

> SiriRide(line_name='25a', license_plate='1234567', operator_ref=4, line_ref=456,
>                         departure_time=datetime.now().time(), journey_ref=234, siri_records=[
>                          SiriRecord(recorded_at=datetime.now().time(), response_timestamp=datetime.now(),
>                                     expected_arrival_time=datetime.now().time(),
>                                     current_location=GeoPoint(12.12, 23.23))])

**Comment by EyalBerger** [comment]
> > pandas/_libs/tslibs/timestamps.pyx in pandas._libs.tslibs.timestamps.Timestamp.tz_convert()
> > TypeError: tz_convert() takes exactly 2 positional arguments (1 given)
> > I changed (locally) self.response_timestamp: datetime = response_timestamp.astimezone() to self.response_timestamp: datetime = response_timestamp.tz_localize('Asia/Tel_Aviv') to make it work.
> 
> it is look like pandas error. i didn't use that library at all. [astimezone()](https://docs.python.org/3/library/datetime.html#datetime.datetime.astimezone) will add to the given timestamp the default OS time zone.

you right. I am using older version of pandas - `Changed in version 3.3: tz now can be omitted`

**Comment by EyalBerger** [comment]
> > SiriRideMongoCrud(MongoCrud(MongoClient(), self.database_name))
> 
> for creating _SiriRideMongoCrud_ object you need to provide _MongoCrud_ instance and for creating this you should provide [MongoClient ](https://api.mongodb.com/python/current/api/pymongo/mongo_client.html#pymongo.mongo_client.MongoClient)instance that configure the connection to mongodb. by default it is trying to connect to localhost with mongodb known port (27017), but you could change it. for example:
> 
> > SiriRideMongoCrud(MongoCrud(MongoClient(host=10.100.34.32, port=5002), "openbus_db"))

Thanks. Are those host and port just examples or those our MongoDB credentials? right now I am writing to my local host.

**Comment by EyalBerger** [comment]
> > I got issues with inserting int attributes (e.g operator_ref) and had to change them to string to make them work.
> 
> in my tests (data_stream/test_data_access_layer.py) i created the following SiriRide and that worked for me. As you can see operator_ref is int (operator_ref=4). Could you provide me the instance that didn't worked for you, so i can add it to my tests?
> 
> > SiriRide(line_name='25a', license_plate='1234567', operator_ref=4, line_ref=456,
> > departure_time=datetime.now().time(), journey_ref=234, siri_records=[
> > SiriRecord(recorded_at=datetime.now().time(), response_timestamp=datetime.now(),
> > expected_arrival_time=datetime.now().time(),
> > current_location=GeoPoint(12.12, 23.23))])

Sure.
This the error - `InvalidDocument: cannot encode object: 3, of type: <class 'numpy.int64'>`
and this is the instance:
`{'type': 'siri_ride',
 'id': None,
 'attributes': {'lineName': nan,
  'licensePlate': '7802069',
  'departureTime': '22:00:00',
  'journeyRef': '47448979',
  'operatorRef': 3,
  'lineRef': '271',
  'siriRecords': [{'recordedAt': '04:50:23',
    'responseTimestamp': '2020-07-01T21:26:48+03:00',
    'expectedArrivalTime': '22:44:00',
    'point': {'type': 'Point', 'coordinates': [0.0, 0.0]}},
   {'recordedAt': '04:50:23',
    'responseTimestamp': '2020-07-01T21:10:48+03:00',
    'expectedArrivalTime': '22:44:00',
    'point': {'type': 'Point', 'coordinates': [0.0, 0.0]}},
   {'recordedAt': '04:50:23',
    'responseTimestamp': '2020-07-01T20:54:48+03:00',
    'expectedArrivalTime': '22:44:00',
    'point': {'type': 'Point', 'coordinates': [0.0, 0.0]}},
   {'recordedAt': '04:01:11',
    'responseTimestamp': '2020-07-01T20:49:48+03:00',
    'expectedArrivalTime': '22:44:00',
    'point': {'type': 'Point', 'coordinates': [0.0, 0.0]}}]}}
`

**Comment by AvivSela** [comment]
> Thanks. Are those host and port just examples or those our MongoDB credentials? right now I am writing to my local host.
Right now there are no mongodb server so it is local. the inputs are example. 

> This the error - InvalidDocument: cannot encode object: 3, of type: <class 'numpy.int64'>

i simulate the scenario: 
``` python
ride = SiriRide(line_name='25a', license_plate='1234567', operator_ref=np.int16(4), line_ref=np.int16(456),
                        departure_time=datetime.now().time(), journey_ref=np.int16(234),
                        siri_records=[SiriRecord(recorded_at=datetime.now().time(),
                                                 response_timestamp=datetime.now(),
                                                 expected_arrival_time=datetime.now().time(),
                                                 current_location=GeoPoint(12.12, 23.23))])
self.crud.create(ride)

```

it seems that mongo library don't know how to handle "numpy int 64". And when it try to convert the object into mongo document before inserting it to db it raise error.

i fixed the issue and add a test for it.

**Pull request merged**
