### PR TITLE
Visualize GPS of one trip

### PR DESCRIPTION
**Pull request by adiwaz**
Jupyter notebook that simulates the visualization of one trip,
using Siri GPS real-time data and GTFS route shape and stops data.

### CODE REVIEW

**Comment by palaviv** [comment]
@adiwaz I think it will be better to upload the notebook without the output of the cells.

**Comment by adiwaz** [comment]
@AvivSela  - it is finished. It represents the conceptual workflow that we would like to do for querying the GTFS&SIRI data in order to get information about a single trip. When the data will be in the cloud we will be able to change the code to read it from there instead of manually downloading files to our computer, and then it would be beneficial to create an API instead of this notebook.

**Comment by cjer** [comment]
@adiwaz @EyalBerger Do we still want this merged, or is this obsolete considering our latest discussions?

**Comment by adiwaz** [comment]
As long as we don't have another better guideline to SIRI data, this can be helpful for newcomers to have a sense of where to start and how to look at the data without being dependent on splunk dashboards.
I am not sure it would have a great importance in a few months from now, and also @EyalBerger should have another visualization notebook which might be more updated.
Merging this or not, we should think about where to store tutorials. We should also keep working on our documentation to have an updated guide for getting started with the data.

**Comment by cjer** [comment]
OK cool, so I am closing this PR for now, can you open the issue for a data newcomers SIRI tutorial?

**Comment by adiwaz** [comment]
@cjer Done. See #230

**Pull request closed without merging**
